# Generated by Django 5.0.3 on 2025-02-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scanned_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('scanned_count', models.IntegerField(default=0)),
            ],
        ),
    ]
