# Generated by Django 5.1.5 on 2025-02-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrscanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='scanned_codes',
            new_name='ScannedCodes',
        ),
    ]
